using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Xml;
using System.Xml.Serialization;
using System.IO;
using System.Globalization;
using MediaBrowser.Library.Extensions;
using MediaBrowser.Library.Configuration;
using MediaBrowser.Library.Localization;
using MediaBrowser.Library.Logging;

//***************************************************************************************************
//  This class is used to extend the string data used by MB.  It is localizable.
//  The most common use will be to provide description strings for config options.  To do this
//  define public string properties that are named the same as the label text of your options on your
//  config panel +desc.  A couple of examples have been generated by the template.
//***************************************************************************************************
namespace Classic
{
    [Serializable]
    public class MyStrings : LocalizedStringData
    {
        private string version = "1.0000"; //this is used to see if we have changed and need to re-save

        //these are our strings keyed by property name
        public string ClassicOptionsDesc = "Options for the Classic Theme.";
        public string ClassicTestOptionDesc = "This option is for the Classic Theme.";

        MyStrings(string file)
        {
            this.FileName = file;
        }

        MyStrings() //for the serializer
        {
        }

        public static MyStrings FromFile(string file)
        {
            MyStrings s;

            if (!File.Exists(file))
            {
                s = new MyStrings(file);
                s.Save();
            }
            Logger.ReportInfo("Using String Data from " + file);
            XmlSerializer xs = new XmlSerializer(typeof(MyStrings));
            using (FileStream fs = new FileStream(file, FileMode.Open, FileAccess.Read, FileShare.Read))
            {
                try
                {
                    s = (MyStrings)xs.Deserialize(fs);
                }
                catch
                {
                    //file is mucked up - just re-create it
                    s = new MyStrings(file);
                }
            }
            if (s.Version != s.version)
            {
                //new version - save over old file
                s = new MyStrings(file);
                s.Version = s.version;
                s.Save();
            }
            return s;
        }
    }
}
