//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diamond {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Diamond.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap BallButtonDark {
            get {
                object obj = ResourceManager.GetObject("BallButtonDark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BallButtonLight {
            get {
                object obj = ResourceManager.GetObject("BallButtonLight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ButtonFocus {
            get {
                object obj = ResourceManager.GetObject("ButtonFocus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap codec_aac {
            get {
                object obj = ResourceManager.GetObject("codec_aac", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap codec_aac_clr {
            get {
                object obj = ResourceManager.GetObject("codec_aac_clr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap codec_ac3 {
            get {
                object obj = ResourceManager.GetObject("codec_ac3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap codec_ac3_clr {
            get {
                object obj = ResourceManager.GetObject("codec_ac3_clr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap codec_asf {
            get {
                object obj = ResourceManager.GetObject("codec_asf", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap codec_asf_clr {
            get {
                object obj = ResourceManager.GetObject("codec_asf_clr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap codec_DD_10 {
            get {
                object obj = ResourceManager.GetObject("codec_DD_10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap codec_DD_10_clr {
            get {
                object obj = ResourceManager.GetObject("codec_DD_10_clr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap codec_DD_20 {
            get {
                object obj = ResourceManager.GetObject("codec_DD_20", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap codec_DD_20_clr {
            get {
                object obj = ResourceManager.GetObject("codec_DD_20_clr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap codec_DD_30 {
            get {
                object obj = ResourceManager.GetObject("codec_DD_30", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap codec_DD_30_clr {
            get {
                object obj = ResourceManager.GetObject("codec_DD_30_clr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap codec_DD_51 {
            get {
                object obj = ResourceManager.GetObject("codec_DD_51", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap codec_DD_51_clr {
            get {
                object obj = ResourceManager.GetObject("codec_DD_51_clr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap codec_DDPlus {
            get {
                object obj = ResourceManager.GetObject("codec_DDPlus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap codec_DDPlus_50 {
            get {
                object obj = ResourceManager.GetObject("codec_DDPlus_50", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap codec_DDPlus_50_clr {
            get {
                object obj = ResourceManager.GetObject("codec_DDPlus_50_clr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap codec_DDPlus_51 {
            get {
                object obj = ResourceManager.GetObject("codec_DDPlus_51", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap codec_DDPlus_51_clr {
            get {
                object obj = ResourceManager.GetObject("codec_DDPlus_51_clr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap codec_DDPlus_61 {
            get {
                object obj = ResourceManager.GetObject("codec_DDPlus_61", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap codec_DDPlus_61_clr {
            get {
                object obj = ResourceManager.GetObject("codec_DDPlus_61_clr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap codec_DDPlus_71 {
            get {
                object obj = ResourceManager.GetObject("codec_DDPlus_71", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap codec_DDPlus_71_clr {
            get {
                object obj = ResourceManager.GetObject("codec_DDPlus_71_clr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap codec_DDPlus_clr {
            get {
                object obj = ResourceManager.GetObject("codec_DDPlus_clr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap codec_DDTrueHD {
            get {
                object obj = ResourceManager.GetObject("codec_DDTrueHD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap codec_DDTrueHD_50 {
            get {
                object obj = ResourceManager.GetObject("codec_DDTrueHD_50", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap codec_DDTrueHD_50_clr {
            get {
                object obj = ResourceManager.GetObject("codec_DDTrueHD_50_clr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap codec_DDTrueHD_51 {
            get {
                object obj = ResourceManager.GetObject("codec_DDTrueHD_51", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap codec_DDTrueHD_51_clr {
            get {
                object obj = ResourceManager.GetObject("codec_DDTrueHD_51_clr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap codec_DDTrueHD_61 {
            get {
                object obj = ResourceManager.GetObject("codec_DDTrueHD_61", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap codec_DDTrueHD_61_clr {
            get {
                object obj = ResourceManager.GetObject("codec_DDTrueHD_61_clr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap codec_DDTrueHD_71 {
            get {
                object obj = ResourceManager.GetObject("codec_DDTrueHD_71", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap codec_DDTrueHD_71_clr {
            get {
                object obj = ResourceManager.GetObject("codec_DDTrueHD_71_clr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap codec_DDTrueHD_clr {
            get {
                object obj = ResourceManager.GetObject("codec_DDTrueHD_clr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap codec_divx {
            get {
                object obj = ResourceManager.GetObject("codec_divx", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap codec_divx_clr {
            get {
                object obj = ResourceManager.GetObject("codec_divx_clr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap codec_dts {
            get {
                object obj = ResourceManager.GetObject("codec_dts", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap codec_DTS_9624 {
            get {
                object obj = ResourceManager.GetObject("codec_DTS_9624", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap codec_DTS_9624_51 {
            get {
                object obj = ResourceManager.GetObject("codec_DTS_9624_51", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap codec_DTS_9624_51_clr {
            get {
                object obj = ResourceManager.GetObject("codec_DTS_9624_51_clr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap codec_DTS_9624_clr {
            get {
                object obj = ResourceManager.GetObject("codec_DTS_9624_clr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap codec_dts_clr {
            get {
                object obj = ResourceManager.GetObject("codec_dts_clr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap codec_DTS_DS {
            get {
                object obj = ResourceManager.GetObject("codec_DTS_DS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap codec_DTS_DS_10 {
            get {
                object obj = ResourceManager.GetObject("codec_DTS_DS_10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap codec_DTS_DS_10_clr {
            get {
                object obj = ResourceManager.GetObject("codec_DTS_DS_10_clr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap codec_DTS_DS_20 {
            get {
                object obj = ResourceManager.GetObject("codec_DTS_DS_20", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap codec_DTS_DS_20_clr {
            get {
                object obj = ResourceManager.GetObject("codec_DTS_DS_20_clr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap codec_DTS_DS_51 {
            get {
                object obj = ResourceManager.GetObject("codec_DTS_DS_51", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap codec_DTS_DS_51_clr {
            get {
                object obj = ResourceManager.GetObject("codec_DTS_DS_51_clr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap codec_DTS_DS_clr {
            get {
                object obj = ResourceManager.GetObject("codec_DTS_DS_clr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap codec_DTS_ES {
            get {
                object obj = ResourceManager.GetObject("codec_DTS_ES", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap codec_DTS_ES_51 {
            get {
                object obj = ResourceManager.GetObject("codec_DTS_ES_51", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap codec_DTS_ES_51_clr {
            get {
                object obj = ResourceManager.GetObject("codec_DTS_ES_51_clr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap codec_DTS_ES_61 {
            get {
                object obj = ResourceManager.GetObject("codec_DTS_ES_61", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap codec_DTS_ES_61_clr {
            get {
                object obj = ResourceManager.GetObject("codec_DTS_ES_61_clr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap codec_DTS_ES_clr {
            get {
                object obj = ResourceManager.GetObject("codec_DTS_ES_clr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap codec_DTS_HD_HRA {
            get {
                object obj = ResourceManager.GetObject("codec_DTS_HD_HRA", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap codec_DTS_HD_HRA_51 {
            get {
                object obj = ResourceManager.GetObject("codec_DTS_HD_HRA_51", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap codec_DTS_HD_HRA_51_clr {
            get {
                object obj = ResourceManager.GetObject("codec_DTS_HD_HRA_51_clr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap codec_DTS_HD_HRA_61 {
            get {
                object obj = ResourceManager.GetObject("codec_DTS_HD_HRA_61", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap codec_DTS_HD_HRA_61_clr {
            get {
                object obj = ResourceManager.GetObject("codec_DTS_HD_HRA_61_clr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap codec_DTS_HD_HRA_71 {
            get {
                object obj = ResourceManager.GetObject("codec_DTS_HD_HRA_71", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap codec_DTS_HD_HRA_71_clr {
            get {
                object obj = ResourceManager.GetObject("codec_DTS_HD_HRA_71_clr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap codec_DTS_HD_HRA_clr {
            get {
                object obj = ResourceManager.GetObject("codec_DTS_HD_HRA_clr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap codec_DTS_HD_MA {
            get {
                object obj = ResourceManager.GetObject("codec_DTS_HD_MA", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap codec_DTS_HD_MA_30_clr {
            get {
                object obj = ResourceManager.GetObject("codec_DTS_HD_MA_30_clr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap codec_DTS_HD_MA_40 {
            get {
                object obj = ResourceManager.GetObject("codec_DTS_HD_MA_40", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap codec_DTS_HD_MA_40_clr {
            get {
                object obj = ResourceManager.GetObject("codec_DTS_HD_MA_40_clr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap codec_DTS_HD_MA_50 {
            get {
                object obj = ResourceManager.GetObject("codec_DTS_HD_MA_50", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap codec_DTS_HD_MA_50_clr {
            get {
                object obj = ResourceManager.GetObject("codec_DTS_HD_MA_50_clr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap codec_DTS_HD_MA_51 {
            get {
                object obj = ResourceManager.GetObject("codec_DTS_HD_MA_51", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap codec_DTS_HD_MA_51_clr {
            get {
                object obj = ResourceManager.GetObject("codec_DTS_HD_MA_51_clr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap codec_DTS_HD_MA_61 {
            get {
                object obj = ResourceManager.GetObject("codec_DTS_HD_MA_61", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap codec_DTS_HD_MA_61_clr {
            get {
                object obj = ResourceManager.GetObject("codec_DTS_HD_MA_61_clr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap codec_DTS_HD_MA_71 {
            get {
                object obj = ResourceManager.GetObject("codec_DTS_HD_MA_71", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap codec_DTS_HD_MA_71_clr {
            get {
                object obj = ResourceManager.GetObject("codec_DTS_HD_MA_71_clr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap codec_DTS_HD_MA_clr {
            get {
                object obj = ResourceManager.GetObject("codec_DTS_HD_MA_clr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap codec_flac {
            get {
                object obj = ResourceManager.GetObject("codec_flac", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap codec_flac_clr {
            get {
                object obj = ResourceManager.GetObject("codec_flac_clr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap codec_h262 {
            get {
                object obj = ResourceManager.GetObject("codec_h262", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap codec_h262_clr {
            get {
                object obj = ResourceManager.GetObject("codec_h262_clr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap codec_h264 {
            get {
                object obj = ResourceManager.GetObject("codec_h264", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap codec_h264_clr {
            get {
                object obj = ResourceManager.GetObject("codec_h264_clr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap codec_mp3 {
            get {
                object obj = ResourceManager.GetObject("codec_mp3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap codec_mp3_clr {
            get {
                object obj = ResourceManager.GetObject("codec_mp3_clr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap codec_mpeg4visual {
            get {
                object obj = ResourceManager.GetObject("codec_mpeg4visual", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap codec_mpeg4visual_clr {
            get {
                object obj = ResourceManager.GetObject("codec_mpeg4visual_clr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap codec_mpegaudio {
            get {
                object obj = ResourceManager.GetObject("codec_mpegaudio", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap codec_mpegaudio_clr {
            get {
                object obj = ResourceManager.GetObject("codec_mpegaudio_clr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap codec_mpegvideo {
            get {
                object obj = ResourceManager.GetObject("codec_mpegvideo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap codec_mpegvideo_clr {
            get {
                object obj = ResourceManager.GetObject("codec_mpegvideo_clr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap codec_on2_vp6 {
            get {
                object obj = ResourceManager.GetObject("codec_on2_vp6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap codec_on2_vp6_clr {
            get {
                object obj = ResourceManager.GetObject("codec_on2_vp6_clr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap codec_sorenson_h263 {
            get {
                object obj = ResourceManager.GetObject("codec_sorenson_h263", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap codec_sorenson_h263_clr {
            get {
                object obj = ResourceManager.GetObject("codec_sorenson_h263_clr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap codec_theora {
            get {
                object obj = ResourceManager.GetObject("codec_theora", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap codec_theora_clr {
            get {
                object obj = ResourceManager.GetObject("codec_theora_clr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap codec_vc1 {
            get {
                object obj = ResourceManager.GetObject("codec_vc1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap codec_vc1_clr {
            get {
                object obj = ResourceManager.GetObject("codec_vc1_clr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap codec_vorbis {
            get {
                object obj = ResourceManager.GetObject("codec_vorbis", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap codec_vorbis_clr {
            get {
                object obj = ResourceManager.GetObject("codec_vorbis_clr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap codec_wma {
            get {
                object obj = ResourceManager.GetObject("codec_wma", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap codec_wma_clr {
            get {
                object obj = ResourceManager.GetObject("codec_wma_clr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap codec_wmv {
            get {
                object obj = ResourceManager.GetObject("codec_wmv", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap codec_wmv_clr {
            get {
                object obj = ResourceManager.GetObject("codec_wmv_clr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap codec_wmv_hd {
            get {
                object obj = ResourceManager.GetObject("codec_wmv_hd", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap codec_wmv_hd_clr {
            get {
                object obj = ResourceManager.GetObject("codec_wmv_hd_clr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap codec_xvid {
            get {
                object obj = ResourceManager.GetObject("codec_xvid", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap codec_xvid_clr {
            get {
                object obj = ResourceManager.GetObject("codec_xvid_clr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] ConfigPanel {
            get {
                object obj = ResourceManager.GetObject("ConfigPanel", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ContextMenu {
            get {
                object obj = ResourceManager.GetObject("ContextMenu", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] CoverflowScroller {
            get {
                object obj = ResourceManager.GetObject("CoverflowScroller", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] DetailMovieView {
            get {
                object obj = ResourceManager.GetObject("DetailMovieView", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap dia_cf_arc {
            get {
                object obj = ResourceManager.GetObject("dia_cf_arc", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap dia_CounterPanel {
            get {
                object obj = ResourceManager.GetObject("dia_CounterPanel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap dia_detailA {
            get {
                object obj = ResourceManager.GetObject("dia_detailA", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap dia_detailB {
            get {
                object obj = ResourceManager.GetObject("dia_detailB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap dia_fbtn_fade {
            get {
                object obj = ResourceManager.GetObject("dia_fbtn_fade", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap dia_folderbutton {
            get {
                object obj = ResourceManager.GetObject("dia_folderbutton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap dia_foldermenu {
            get {
                object obj = ResourceManager.GetObject("dia_foldermenu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap dia_infoPanel {
            get {
                object obj = ResourceManager.GetObject("dia_infoPanel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap dia_list_bg {
            get {
                object obj = ResourceManager.GetObject("dia_list_bg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap dia_list_focus {
            get {
                object obj = ResourceManager.GetObject("dia_list_focus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap dia_pagePanel {
            get {
                object obj = ResourceManager.GetObject("dia_pagePanel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap dia_timePanel {
            get {
                object obj = ResourceManager.GetObject("dia_timePanel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap dia_titlePanel {
            get {
                object obj = ResourceManager.GetObject("dia_titlePanel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap dia_TopPanel {
            get {
                object obj = ResourceManager.GetObject("dia_TopPanel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] DiamondBackdrop {
            get {
                object obj = ResourceManager.GetObject("DiamondBackdrop", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] DiamondBall {
            get {
                object obj = ResourceManager.GetObject("DiamondBall", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] DiamondFolderMenu {
            get {
                object obj = ResourceManager.GetObject("DiamondFolderMenu", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] DiamondFontsDefault {
            get {
                object obj = ResourceManager.GetObject("DiamondFontsDefault", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] DiamondFontsSmall {
            get {
                object obj = ResourceManager.GetObject("DiamondFontsSmall", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] DiamondInfo {
            get {
                object obj = ResourceManager.GetObject("DiamondInfo", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] DiamondListAlbum {
            get {
                object obj = ResourceManager.GetObject("DiamondListAlbum", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] DiamondListView {
            get {
                object obj = ResourceManager.GetObject("DiamondListView", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DiamondMainBG {
            get {
                object obj = ResourceManager.GetObject("DiamondMainBG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] DiamondMediaInfoPanel {
            get {
                object obj = ResourceManager.GetObject("DiamondMediaInfoPanel", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] DiamondPagination {
            get {
                object obj = ResourceManager.GetObject("DiamondPagination", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] DiamondSpin {
            get {
                object obj = ResourceManager.GetObject("DiamondSpin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] DiamondStylesDefault {
            get {
                object obj = ResourceManager.GetObject("DiamondStylesDefault", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] DiamondTab {
            get {
                object obj = ResourceManager.GetObject("DiamondTab", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] DiamondText {
            get {
                object obj = ResourceManager.GetObject("DiamondText", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] DiamondToolBox {
            get {
                object obj = ResourceManager.GetObject("DiamondToolBox", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] FocusSelector {
            get {
                object obj = ResourceManager.GetObject("FocusSelector", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap folder {
            get {
                object obj = ResourceManager.GetObject("folder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HD {
            get {
                object obj = ResourceManager.GetObject("HD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap hd1080 {
            get {
                object obj = ResourceManager.GetObject("hd1080", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap hd720 {
            get {
                object obj = ResourceManager.GetObject("hd720", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap hdtype_1080 {
            get {
                object obj = ResourceManager.GetObject("hdtype_1080", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap hdtype_1080_clr {
            get {
                object obj = ResourceManager.GetObject("hdtype_1080_clr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap hdtype_720 {
            get {
                object obj = ResourceManager.GetObject("hdtype_720", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap hdtype_720_clr {
            get {
                object obj = ResourceManager.GetObject("hdtype_720_clr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IconActors {
            get {
                object obj = ResourceManager.GetObject("IconActors", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IconAdd {
            get {
                object obj = ResourceManager.GetObject("IconAdd", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IconAdded {
            get {
                object obj = ResourceManager.GetObject("IconAdded", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IconArrowDown {
            get {
                object obj = ResourceManager.GetObject("IconArrowDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IconArrowUp {
            get {
                object obj = ResourceManager.GetObject("IconArrowUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IconBanner {
            get {
                object obj = ResourceManager.GetObject("IconBanner", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IconConfig {
            get {
                object obj = ResourceManager.GetObject("IconConfig", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IconDelete {
            get {
                object obj = ResourceManager.GetObject("IconDelete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IconFloral {
            get {
                object obj = ResourceManager.GetObject("IconFloral", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IconGears {
            get {
                object obj = ResourceManager.GetObject("IconGears", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IconIndex {
            get {
                object obj = ResourceManager.GetObject("IconIndex", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IconLabels {
            get {
                object obj = ResourceManager.GetObject("IconLabels", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IconLines {
            get {
                object obj = ResourceManager.GetObject("IconLines", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IconLock {
            get {
                object obj = ResourceManager.GetObject("IconLock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IconMusic {
            get {
                object obj = ResourceManager.GetObject("IconMusic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IconPlay {
            get {
                object obj = ResourceManager.GetObject("IconPlay", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IconRefresh {
            get {
                object obj = ResourceManager.GetObject("IconRefresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IconRemote {
            get {
                object obj = ResourceManager.GetObject("IconRemote", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IconResume {
            get {
                object obj = ResourceManager.GetObject("IconResume", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IconRT {
            get {
                object obj = ResourceManager.GetObject("IconRT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IconShuffle {
            get {
                object obj = ResourceManager.GetObject("IconShuffle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IconSort {
            get {
                object obj = ResourceManager.GetObject("IconSort", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IconSummary {
            get {
                object obj = ResourceManager.GetObject("IconSummary", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IconTrailers {
            get {
                object obj = ResourceManager.GetObject("IconTrailers", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IconUnLock {
            get {
                object obj = ResourceManager.GetObject("IconUnLock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IconVertical {
            get {
                object obj = ResourceManager.GetObject("IconVertical", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IconWatched {
            get {
                object obj = ResourceManager.GetObject("IconWatched", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] Images {
            get {
                object obj = ResourceManager.GetObject("Images", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ItemButton {
            get {
                object obj = ResourceManager.GetObject("ItemButton", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] LayoutAlbum {
            get {
                object obj = ResourceManager.GetObject("LayoutAlbum", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] LayoutCoverflow {
            get {
                object obj = ResourceManager.GetObject("LayoutCoverflow", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] LayoutCoverflow2 {
            get {
                object obj = ResourceManager.GetObject("LayoutCoverflow2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] LayoutDetails {
            get {
                object obj = ResourceManager.GetObject("LayoutDetails", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] LayoutPoster {
            get {
                object obj = ResourceManager.GetObject("LayoutPoster", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] LayoutRoot {
            get {
                object obj = ResourceManager.GetObject("LayoutRoot", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] LayoutThumb {
            get {
                object obj = ResourceManager.GetObject("LayoutThumb", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] LayoutThumbStrip {
            get {
                object obj = ResourceManager.GetObject("LayoutThumbStrip", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap media_3gp {
            get {
                object obj = ResourceManager.GetObject("media_3gp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap media_3gp_clr {
            get {
                object obj = ResourceManager.GetObject("media_3gp_clr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap media_asf {
            get {
                object obj = ResourceManager.GetObject("media_asf", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap media_asf_clr {
            get {
                object obj = ResourceManager.GetObject("media_asf_clr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap media_avi {
            get {
                object obj = ResourceManager.GetObject("media_avi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap media_avi_clr {
            get {
                object obj = ResourceManager.GetObject("media_avi_clr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap media_bluray {
            get {
                object obj = ResourceManager.GetObject("media_bluray", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap media_bluray_clr {
            get {
                object obj = ResourceManager.GetObject("media_bluray_clr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap media_dvd {
            get {
                object obj = ResourceManager.GetObject("media_dvd", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap media_dvd_clr {
            get {
                object obj = ResourceManager.GetObject("media_dvd_clr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap media_dvrms {
            get {
                object obj = ResourceManager.GetObject("media_dvrms", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap media_dvrms_clr {
            get {
                object obj = ResourceManager.GetObject("media_dvrms_clr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap media_flv {
            get {
                object obj = ResourceManager.GetObject("media_flv", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap media_flv_clr {
            get {
                object obj = ResourceManager.GetObject("media_flv_clr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap media_hddvd {
            get {
                object obj = ResourceManager.GetObject("media_hddvd", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap media_hddvd_clr {
            get {
                object obj = ResourceManager.GetObject("media_hddvd_clr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap media_iso {
            get {
                object obj = ResourceManager.GetObject("media_iso", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap media_iso_clr {
            get {
                object obj = ResourceManager.GetObject("media_iso_clr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap media_m2ts {
            get {
                object obj = ResourceManager.GetObject("media_m2ts", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap media_m2ts_clr {
            get {
                object obj = ResourceManager.GetObject("media_m2ts_clr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap media_mkv {
            get {
                object obj = ResourceManager.GetObject("media_mkv", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap media_mkv_clr {
            get {
                object obj = ResourceManager.GetObject("media_mkv_clr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap media_mov {
            get {
                object obj = ResourceManager.GetObject("media_mov", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap media_mov_clr {
            get {
                object obj = ResourceManager.GetObject("media_mov_clr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap media_mp4 {
            get {
                object obj = ResourceManager.GetObject("media_mp4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap media_mp4_clr {
            get {
                object obj = ResourceManager.GetObject("media_mp4_clr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap media_mpeg {
            get {
                object obj = ResourceManager.GetObject("media_mpeg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap media_mpeg_clr {
            get {
                object obj = ResourceManager.GetObject("media_mpeg_clr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap media_ogg {
            get {
                object obj = ResourceManager.GetObject("media_ogg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap media_ogg_clr {
            get {
                object obj = ResourceManager.GetObject("media_ogg_clr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap media_ts {
            get {
                object obj = ResourceManager.GetObject("media_ts", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap media_ts_clr {
            get {
                object obj = ResourceManager.GetObject("media_ts_clr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap media_wmv {
            get {
                object obj = ResourceManager.GetObject("media_wmv", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap media_wmv_clr {
            get {
                object obj = ResourceManager.GetObject("media_wmv_clr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap media_wtv {
            get {
                object obj = ResourceManager.GetObject("media_wtv", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap media_wtv_clr {
            get {
                object obj = ResourceManager.GetObject("media_wtv_clr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] Page {
            get {
                object obj = ResourceManager.GetObject("Page", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] PageDetailArea {
            get {
                object obj = ResourceManager.GetObject("PageDetailArea", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] PersonButton {
            get {
                object obj = ResourceManager.GetObject("PersonButton", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] PosterScroller {
            get {
                object obj = ResourceManager.GetObject("PosterScroller", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] PosterViewItem {
            get {
                object obj = ResourceManager.GetObject("PosterViewItem", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ratio_133 {
            get {
                object obj = ResourceManager.GetObject("ratio_133", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ratio_133_clr {
            get {
                object obj = ResourceManager.GetObject("ratio_133_clr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ratio_137 {
            get {
                object obj = ResourceManager.GetObject("ratio_137", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ratio_137_clr {
            get {
                object obj = ResourceManager.GetObject("ratio_137_clr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ratio_143 {
            get {
                object obj = ResourceManager.GetObject("ratio_143", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ratio_143_clr {
            get {
                object obj = ResourceManager.GetObject("ratio_143_clr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ratio_144 {
            get {
                object obj = ResourceManager.GetObject("ratio_144", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ratio_144_clr {
            get {
                object obj = ResourceManager.GetObject("ratio_144_clr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ratio_150 {
            get {
                object obj = ResourceManager.GetObject("ratio_150", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ratio_150_clr {
            get {
                object obj = ResourceManager.GetObject("ratio_150_clr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ratio_156 {
            get {
                object obj = ResourceManager.GetObject("ratio_156", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ratio_156_clr {
            get {
                object obj = ResourceManager.GetObject("ratio_156_clr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ratio_166 {
            get {
                object obj = ResourceManager.GetObject("ratio_166", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ratio_166_clr {
            get {
                object obj = ResourceManager.GetObject("ratio_166_clr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ratio_177 {
            get {
                object obj = ResourceManager.GetObject("ratio_177", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ratio_177_clr {
            get {
                object obj = ResourceManager.GetObject("ratio_177_clr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ratio_178 {
            get {
                object obj = ResourceManager.GetObject("ratio_178", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ratio_178_clr {
            get {
                object obj = ResourceManager.GetObject("ratio_178_clr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ratio_181 {
            get {
                object obj = ResourceManager.GetObject("ratio_181", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ratio_181_clr {
            get {
                object obj = ResourceManager.GetObject("ratio_181_clr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ratio_185 {
            get {
                object obj = ResourceManager.GetObject("ratio_185", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ratio_185_clr {
            get {
                object obj = ResourceManager.GetObject("ratio_185_clr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ratio_200 {
            get {
                object obj = ResourceManager.GetObject("ratio_200", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ratio_200_clr {
            get {
                object obj = ResourceManager.GetObject("ratio_200_clr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ratio_220 {
            get {
                object obj = ResourceManager.GetObject("ratio_220", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ratio_220_clr {
            get {
                object obj = ResourceManager.GetObject("ratio_220_clr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ratio_235 {
            get {
                object obj = ResourceManager.GetObject("ratio_235", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ratio_235_clr {
            get {
                object obj = ResourceManager.GetObject("ratio_235_clr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ratio_239 {
            get {
                object obj = ResourceManager.GetObject("ratio_239", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ratio_239_clr {
            get {
                object obj = ResourceManager.GetObject("ratio_239_clr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ratio_240 {
            get {
                object obj = ResourceManager.GetObject("ratio_240", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ratio_240_clr {
            get {
                object obj = ResourceManager.GetObject("ratio_240_clr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ratio_255 {
            get {
                object obj = ResourceManager.GetObject("ratio_255", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ratio_255_clr {
            get {
                object obj = ResourceManager.GetObject("ratio_255_clr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ratio_259 {
            get {
                object obj = ResourceManager.GetObject("ratio_259", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ratio_259_clr {
            get {
                object obj = ResourceManager.GetObject("ratio_259_clr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ratio_266 {
            get {
                object obj = ResourceManager.GetObject("ratio_266", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ratio_266_clr {
            get {
                object obj = ResourceManager.GetObject("ratio_266_clr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ratio_276 {
            get {
                object obj = ResourceManager.GetObject("ratio_276", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ratio_276_clr {
            get {
                object obj = ResourceManager.GetObject("ratio_276_clr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ratio_400 {
            get {
                object obj = ResourceManager.GetObject("ratio_400", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ratio_400_clr {
            get {
                object obj = ResourceManager.GetObject("ratio_400_clr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RectLight {
            get {
                object obj = ResourceManager.GetObject("RectLight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap star_empty {
            get {
                object obj = ResourceManager.GetObject("star_empty", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap star_full {
            get {
                object obj = ResourceManager.GetObject("star_full", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap star_half {
            get {
                object obj = ResourceManager.GetObject("star_half", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] StarRating {
            get {
                object obj = ResourceManager.GetObject("StarRating", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ThumbStripScroller {
            get {
                object obj = ResourceManager.GetObject("ThumbStripScroller", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Weather {
            get {
                object obj = ResourceManager.GetObject("Weather", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap zoompane {
            get {
                object obj = ResourceManager.GetObject("zoompane", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
